### PR TITLE
display fixes and optimizations

### PR DESCRIPTION
**Pull request by npitre**

### CODE REVIEW

**Comment by andmarti1424** [comment]
Thank you for this.  Will take a look at it.
Are you confident on not breaking anything with this, since I plan on making a release in a couple of days.

I was about to ask you about how difficult was to read the functions you modified when I saw your comment.
Have you take a look at the ui code of sc? I believe current code is much more polished and tidier.

Btw, if you want to enhance, why use int for configuration values when you can use unsigned short??

**Comment by andmarti1424** [comment]
btw, theres is a bug in the whole procedure I couldnt figure out and is as follow:
(my terminal is 40 LINES long).

open clean ./sc-im
go to A66 with 'j'
freeze that row with fr
go to A67 with 'j'
fr again
go to A112 and freeze the row
go to A113 and freeze the row
go to A158 and freeze the row
go to A159 and freeze the row
go to A200 with 'j'.
Everything is fine up to here..
go up with 'k' until row 159 is the lower row visible
go up again with 'k'. row 159 is still visible, but row 158 not. BUG
go up again and now row 158 appears again..
go up again with 'k' until you have at the bottom the rows 159,158,113 and 112.
go up again with 'k', 159 158 remain at the bottom. but rows 113 and 112 disappear.
you can go up until A0
the rows 159 158 113 and 112 wont show up but
the curious thing is that here it shows:
first 30 rows, below that row 30, the rows 66 and 67 which are frozen,
and below that rows 68 69 70 and 71, which are not frozen, but those should have been
rows 159 158 113 and 112.

I just couldnt figure it out. too much for my ruined brain.

**Comment by npitre** [comment]
On Tue, 11 May 2021, Andrés Martinelli wrote:

> btw, theres is a bug in the whole procedure I couldnt figure out and is as follow:

OK. I understand the problem.

I'll think of a way to fix that.

**Comment by andmarti1424** [comment]
I believe its just failing to ignore the rows passed 'rows' (I believe you renamed it to row_boundary) which are not frozen..

**Comment by npitre** [comment]
> calc_offscr_sc.. functions I believe are as simple as they can be, to support the frozen areas and format (rows higher than 1 for example).

Well... I now have my own version which is simpler and supports all 
cases (I think).

Please have a look at the `multifreeze` branch of 
`https://github.com/npitre/sc-im/`.

Let me know what you think.

**Comment by andmarti1424** [comment]
First, thanks for your work. I think you changed a lot. More than needed.
Dont really think its more understandable but anyways the thing is cannot test it. Fails the building for me:

-DODS -DXLSX -I/usr/include/libxml2  -DXLSX_EXPORT  -DXLUA    -c -o cmds_command.o cmds_command.c
cmds_command.c: In function ‘do_commandmode’:
cmds_command.c:614:13: error: ‘center_hidden_rows’ undeclared (first use in this function)
  614 |             center_hidden_rows = 0;
      |             ^~~~~~~~~~~~~~~~~~
cmds_command.c:614:13: note: each undeclared identifier is reported only once for each function it appears in
cmds_command.c:615:13: error: ‘center_hidden_cols’ undeclared (first use in this function)
  615 |             center_hidden_cols = 0;
      |             ^~~~~~~~~~~~~~~~~~
make: *** [<builtin>: cmds_command.o] Error 1

**Comment by andmarti1424** [comment]
I commented those lines and managed to finish the buiding. But It just doesnt work now. I start it and move the cursor one position and cuts the rows to 15.
image

If i go to a cell outside the visible grid, the grid doesnt update and cursor dissappears.
image

Frozen rows does not work either. If I freeze a row it just freeze the whole grid (well what it shows of the grid).
Column movement seems to work ok when you dont freeze anything. Once you freeze, it has some problems to. For instance here it hidded current column

image

**Comment by andmarti1424** [comment]
I think we should keep the current code and just add the two if's to ignore the rows passed row_boundary which are not frozen..

**Comment by npitre** [comment]
On Wed, 12 May 2021, Andrés Martinelli wrote:

> First, thanks for your work. I think you changed a lot. More than needed.

You think?  I tried to keep the changes small. It didn't work.

> Dont really think its more understandable but anyways the thing is cannot test it. Fails the building for me:

Please try again.

**Comment by npitre** [comment]
On Wed, 12 May 2021, Andrés Martinelli wrote:

> I commented those lines and managed to finish the buiding. But It just doesnt work now. I start it and move the cursor one position and cuts the rows to 15.
> image

Remember I'm blind and cannot see those images.

Of course I didn't expect everything to work on the first try... 
especially not at 4am.  ;-)

**Comment by npitre** [comment]
On Wed, 12 May 2021, Andrés Martinelli wrote:

> I think we should keep the current code and just add the two if's to ignore the rows passed row_boundary which are not frozen..

That won't solve all the scroll movements, nor the center moves, etc. 
Those are still broken and adding more quick hacks won't improve the 
situation.

**Comment by andmarti1424** [comment]
Sorry. Yes. Didnt have that in my mind at the moment

**Comment by andmarti1424** [comment]
No, it still fails. It only shows the first 15 rows.
The column movements works better but it still fails to show the cursor sometimes when there are frozen columns...

**Comment by andmarti1424** [comment]
@npitre Please take a look at my latest commit.

btw, havent noticed missbehaviours in the scroll movements, nor the center moves..

**Comment by npitre** [comment]
> No, it still fails. It only shows the first 15 rows.

DOH!

The first fix worth mentioning:

```
--- a/src/tui.c
+++ b/src/tui.c
@@ -430,7 +430,7 @@ void ui_update(int header) {
      * frozen rows/cols, the fewer mobile rows/cols.
      */
     int nb_mobile_cols = calc_mobile_cols(NULL);
-    int nb_mobile_rows = calc_mobile_cols(NULL);
+    int nb_mobile_rows = calc_mobile_rows(NULL);
 
```

That should help a little bit.  ;-)

**Comment by andmarti1424** [comment]
Now we are talking! It seems to work fine. Way better than mine thats for sure! Thanks.

When you have time and feel like it... could you please document a little more the whole work?
Variables you used / their purpose. even the functions start without telling their purpose, the parameters and their return values.. 
Everything that could help everyone understand the code in the future..
Thanks for your work and time.

**Comment by npitre** [comment]
Absolutely. I'll do some cleanups and document the critical functions.
Then I'll send you a PR.

I found other minor bugs that I'm folding in as well.

**Comment by andmarti1424** [comment]
Great. I then avoid making commits until your PR.
What did you find?

**Pull request merged**
