### PR TITLE
Markdown export with command :e mkd file.md

### PR DESCRIPTION
**Pull request by mipmip**
implements #379

### CODE REVIEW

**Comment by andmarti1424** [comment]
this is great. thanks! could you please update doc file as well with this new command?

**Comment by mipmip** [comment]
> this is great. thanks! could you please update doc file as well with this new command?

Thanks for merging, I needed this. Happy you're happy. I'll send a PR for the doc tomorrow.

**Comment by andmarti1424** [comment]
Hello @mipmip. I have added support for having rows that are more than 1 LINE height. And that impacted on so many places.
I have also rearranged plain text export to handle that. Is there a chance you rearrange the markdown export to handle it as well?? Thanks.

**Comment by andmarti1424** [comment]
I have commited some changes to accomplish the above, but it still has some cases to be fixed with empty cells.
Hasnt figured it out yet.

**Comment by andmarti1424** [comment]
@mipmip i think i got it fixed now.
btw i have also changed the order of some of your code cause it didnt export correctly when having empty column at left of data..

**Comment by mipmip** [comment]
Thanks @andmarti1424. I'll try to find time to come back and help with Sc-im. I guess https://github.com/mipmip/vim-scimark is now almost compatible with the main sc-im tree.

**Comment by andmarti1424** [comment]
Yes that would be great @mipmip.you can now reference to main stream. A lot of stuff was added and fixed lately.

**Pull request merged**
