### PR TITLE
Strtonum

### PR DESCRIPTION
**Pull request by wimstockman**
Added a function :strtonum to convert string field to numerc field.
Did not added the undo capability for it.
Maybe you can take a look at it for the undo andmarti ?

Kind regards,
Wim

### CODE REVIEW

**Comment by andmarti1424** [comment]
Does this replace the #435 PR ??

**Comment by wimstockman** [comment]
Yes, it combines both the new function and the fix.

**Comment by andmarti1424** [comment]
Thanks!

**Comment by wimstockman** [comment]
Could you help me explain how the undo/redo works because I do not understand it yet.
Kind regards
Wim

**Comment by andmarti1424** [comment]
yes, the idea is you create and undo struct. then save status of the ents you are going to modify. then you do the change and you then save the status after the mod...
Take a look at the function del_selected_cells in cmds.c
It is called for instance when you press 'x' in normal mode.

**Comment by wimstockman** [comment]
Ok , I ll take a look thx

**Comment by andmarti1424** [comment]
Updated last comment.
An example could be:

#ifdef UNDO
create_undo_action();                                          
copy_to_undostruct(currow, curcol, currow, curcol, 'd');
#endif

# do some stuff here

#ifdef UNDO
copy_to_undostruct(currow, curcol, currow, curcol, 'a');     
end_undo_action();
#endif

of course this is a simple example. take a look at undo.c

**Comment by EdwardWong1994** [comment]
> Ok , I ll take a look thx

Hello, Wim

I copy the data from one spreadsheet to sc-im, it is string  and i try to use `:strtonum A4:A293`, but only the last one value is changed and other remaining values are still string. 
Xnip2022-09-01_14-08-16

Xnip2022-09-01_14-08-26

 Would be kind of you to provide some hints?  I encounter a lot of case need to transfer data from string to numeric values

**Pull request merged**
