### PR TITLE
added xlsx sheet selection

### PR DESCRIPTION
**Pull request by dvhar**
Added the --sheet option to pick a sheet when loading an xlsx file

### CODE REVIEW

**Comment by andmarti1424** [comment]
Great workarround. Will merge this

**Comment by dvhar** [comment]
Thanks. I just made another commit so if the sheet option is just a number like "--sheet=2", it will be treated like "--sheet=sheet2". Was trying to be concise, hope it's not too messy.

**Comment by mschilli87** [comment]
@dvhar:
> On second thought, that would mess with sheets that have numerical names. May want to stick with the previous commit.

How about first trying to open the sheet by the given name as-is, and only upon failure (and the sheet name is a number) prefix it by `"sheet"` and try again before ultimately giving up and reporting failure?

**Comment by dvhar** [comment]
I should have learned about xlsx files a bit more before commenting. Turns out the worksheet files are all just named "sheet#.xml" so it's not a problem. Selecting worksheets by name rather than the standard sheet# would be a nice feature to add and I'll look into doing that, but this solution works fine for now.

**Comment by dvhar** [comment]
Sheet name selection works now. Uses actually sheet names, not just the xml file names. Selection by sheet number also still works.

**Comment by andmarti1424** [comment]
Coul you please update 'doc' file as well? Thanks!

**Comment by andmarti1424** [comment]
Thanks for your work!

**Pull request merged**
