### PR TITLE
Make colors configurable

### PR DESCRIPTION
**Pull request by jsvana**
This allows users to configure colors at runtime via a configuration file at `$XDG_CONFIG_HOME/scim/config`

### CODE REVIEW

**Comment by andmarti1424** [comment]
Colors can already been configured at runtime. And you can also store their definitions in.scimrc of you $HOME.

**Comment by jsvana** [comment]
Oh, interesting! I didn't see anything like that when I was poking around, and it seems like configuration simply set values for unrelated properties. Is there documentation for this?

**Comment by andmarti1424** [comment]
You can also redefine the basic ncurses colors specifying a rgb value. Your terminal must support 256 colos

**Comment by jsvana** [comment]
Never mind, found it here: https://github.com/andmarti1424/sc-im/wiki/White-background. As for the colors themselves, that's true but it didn't look like you could change which color ID (COLOR_RED, COLOR_MAGENTA, etc.) was picked for which thing. Sorry for the bogus PR :)

**Comment by andmarti1424** [comment]
Its in the doc. Check :color :cellcolor and :redefine_color functions described in :help

**Pull request closed without merging**
