### PR TITLE
Translate comments

### PR DESCRIPTION
**Pull request by alx741**
Ok, apparently some merge conflicts where unsolved, but after fix them new conflicts appeared relative to master and everything becomes a huge mess.

So here it is again in a new branch: the translations + the corrections were applied and now it compiles.

### CODE REVIEW

**Comment by andmarti1424** [comment]
Success. Great job.

**Comment by andmarti1424** [comment]
Hello. Did you based on the main branch or dev branch to do this work?

**Comment by andmarti1424** [comment]
I see you took the main branch. This was my mistake as I should have put the dev branch as the default for pull requests. But now I have both branches messed up, with latest dev branch commits!!

**Comment by andmarti1424** [comment]
I believe I fixed them and now are equal. Now the dev branch is the default branch for pull requests..

**Comment by alx741** [comment]
Yep, i used master. Let me know if help is needed with that

**Comment by andmarti1424** [comment]
Thanks. I changed in the github conf and now dev is the default branch for
pull requests.
I am now fixing some issues with the encoding, but I have noticed the
source files at utils dir are not translated.

2016-02-12 12:26 GMT-03:00 Daniel Campoverde Carrión [alx741] <
notifications@github.com>:

> Yep, i used master. Let me know if help is needed with that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/sc-im/pull/49#issuecomment-183372917>.
>



-- 
Andrés Martinelli

**Comment by alx741** [comment]
Fool of me, didn't even notice the utils dir! Working on it...

**Pull request merged**
