### PR TITLE
more fix/optimization to the display code

### PR DESCRIPTION
**Pull request by npitre**
Simplify the multi-row display logic.
Don't destroy the `out` array as the code that follows needs it.
Revert to single-row cells when the autowrap config is unset.

### CODE REVIEW

**Comment by npitre** [comment]
> btw if you want to continue helping.. you can take a look at pad_and_align(). it should handle alignment when rowformat > 1. that is not done yet.

What kind of alignment would you expect in that case?

**Comment by andmarti1424** [comment]
Try entering a long text that does not fit in a 1 row cell.
Increase it to 2 row height with `fj`.
Then you should be able to align the text to left, right or center with `{` `}` `|` 
Currently it only shows it left aligned.

**Comment by andmarti1424** [comment]
ideally pad_and_align should call a new function that add white spaces to fill an specific width..

**Comment by npitre** [comment]
On Wed, 19 May 2021, Andrés Martinelli wrote:

> Then you should be able to align the text to left, right or center with `{` `}` `|` 

If the text doesn't fit in the column width, then by definition the 
first line of the cell can't be justified as it is flush with the cell 
limits.

There would be a need for line wrapping on word boundaries first.

**Comment by andmarti1424** [comment]
hello @npitre . I created a new branch for multisheet support. Have you take a look at it?

btw. Making tests in all bunch of stuff I have noticed that one of the csv examples (l1.csv and l2.csv files of examples folder) is giving invalid read on calc_mobile_cols (cmds.c:2547)
that is when its trying to read row_frozen..
I still havent figured out why its failing, and why there, cause in this example is reallocating new columns, not new rows.
if you can take a look at it and feel like it... really appreciate it.
Thanks.

**Comment by npitre** [comment]
> hello @npitre . I created a new branch for multisheet support. Have you take a look at it?

Looks neat!

Might be a good idea to pass sh down to helper functions and not fetch 
it from `session->cur_doc->cur_sh` everywhere.

> btw. Making tests in all bunch of stuff I have noticed that one of the 
> csv examples (l1.csv and l2.csv files of examples folder) is giving 
> invalid read on calc_mobile_cols (cmds.c:2547)
> that is when its trying to read row_frozen..
> I still havent figured out why its failing, and why there, cause in 
> this example is reallocating new columns, not new rows.
> if you can take a look at it and feel like it... really appreciate it.

What is wrong with it exactly? Seems to work OK here.

**Comment by andmarti1424** [comment]
yes.  `session->cur_doc->cur_sh` was to get it started. I am changing a lot functions to take a new parameter for the sheet.

this is what Valgrind says when opening those files..

` ==3482== 76 errors in context 1 of 2:
227 ==3482== Invalid read of size 1
228 ==3482==    at 0x11EBD8: calc_mobile_cols (cmds.c:2548)
229 ==3482==    by 0x155138: ui_update (tui.c:437)
230 ==3482==    by 0x1257D8: do_commandmode (cmds_command.c:1168)
231 ==3482==    by 0x142BB6: exec_single_cmd (input.c:341)
232 ==3482==    by 0x142D1A: exec_mult (input.c:401)
233 ==3482==    by 0x142C76: handle_mult (input.c:377)
234 ==3482==    by 0x14282C: handle_input (input.c:214)
235 ==3482==    by 0x14D492: main (main.c:344)
236 ==3482==  Address 0x7689ac4 is 0 bytes after a block of size 100 alloc'd
237 ==3482==    at 0x483E7C5: malloc (vg_replace_malloc.c:380)
238 ==3482==    by 0x15FA3D: scxmalloc (xmalloc.c:75)
239 ==3482==    by 0x15FA7D: scxrealloc (xmalloc.c:97)
240 ==3482==    by 0x15CAB5: growtbl (vmtbl.c:209)
241 ==3482==    by 0x13AABE: load_file (file.c:2221)
242 ==3482==    by 0x14D30F: main (main.c:277)
243 ==3482==¬
244 ==3482==¬
245 ==3482== 76 errors in context 2 of 2:
246 ==3482== Invalid read of size 1
247 ==3482==    at 0x11EBD8: calc_mobile_cols (cmds.c:2548)
248 ==3482==    by 0x155138: ui_update (tui.c:437)
249 ==3482==    by 0x14D3B0: main (main.c:311)
250 ==3482==  Address 0x7689ac4 is 0 bytes after a block of size 100 alloc'd
251 ==3482==    at 0x483E7C5: malloc (vg_replace_malloc.c:380)
252 ==3482==    by 0x15FA3D: scxmalloc (xmalloc.c:75)
253 ==3482==    by 0x15FA7D: scxrealloc (xmalloc.c:97)
254 ==3482==    by 0x15CAB5: growtbl (vmtbl.c:209)
255 ==3482==    by 0x13AABE: load_file (file.c:2221)
256 ==3482==    by 0x14D30F: main (main.c:277)
`

**Comment by npitre** [comment]
On Mon, 24 May 2021, Andrés Martinelli wrote:

> ` ==3482== 76 errors in context 1 of 2:
> 227 ==3482== Invalid read of size 1
> 228 ==3482==    at 0x11EBD8: calc_mobile_cols (cmds.c:2548)

Oops. Here's the fix:

```
diff --git a/src/cmds.c b/src/cmds.c
index 2128c71..452dc0d 100644
--- a/src/cmds.c
+++ b/src/cmds.c
@@ -2545,7 +2545,7 @@ int calc_mobile_cols(int *last_p) {
     sh->nb_frozen_cols = 0;
     sh->nb_frozen_screencols = 0;
     for (i = 0; i < sh->maxcols; i++) {
-        if (sh->row_frozen[i])
+        if (sh->col_hidden[i])
             continue;
         if (sh->col_frozen[i]) {
             sh->nb_frozen_cols++;
```

**Comment by andmarti1424** [comment]
Ohhh. I should have noticed that. Thank you.
Commited.

**Comment by npitre** [comment]
On Mon, 24 May 2021, Andrés Martinelli wrote:

> Ohhh. I should have noticed that. Thank you.
> Commited.

Same fix is needed in the main branch as well.
BTW why is it called "freeze" ?

**Comment by andmarti1424** [comment]
It will eventually come to freeze when merging multisheet branch. Yes. Freeze is the main branch. Should be called main. It was renamed some long time ago. Should be renamed back though.

**Pull request merged**
