### PR TITLE
Fix/ncurses libs

### PR DESCRIPTION
**Pull request by melak**

### CODE REVIEW

**Comment by andmarti1424** [comment]
Hello. where you had that ncurses build issue? What is your OS ?

**Comment by melak** [comment]
FreeBSD with ncurses from base.

**Comment by andmarti1424** [comment]
Ok. About the bsdmakefile, how would you use it? Wouldn't just call gmake build it?

**Comment by melak** [comment]
gmake works too, obviously, BSDmakefile just makes it convenient. If your make is GNU make, it doesn't come in the picture at all. If your make is BSD make, this BSDmakefile invokes the GNU one with the original arguments (target specs and variables). It's just a convenience gimmick.

**Comment by andmarti1424** [comment]
Merged! Could you please update the wiki of FreeBSD as well?

**Comment by yokattana** [comment]
I was working on a very similar commit. Vanilla macOS needs a similar setup but with plain ncurses (non-w) instead.

**Comment by melak** [comment]
@yokattana, you could try something like this:
```
diff --git a/src/Makefile b/src/Makefile
index 167f4ea..d7d637f 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -20,7 +20,11 @@ MANDIR  = $(prefix)/man/man1
 
 ifeq ($(shell pkg-config --exists ncursesw || echo 'no'),no)
 NCURSES_CFLAGS ?=
+ifneq ($(filter $(OS),Darwin),)
+NCURSES_LIBS ?= -lncurses
+else
 NCURSES_LIBS ?= -lncursesw
+endif
 else
 NCURSES_CFLAGS := $(shell pkg-config --cflags ncursesw)
 NCURSES_LIBS := $(shell pkg-config --libs ncursesw)
```
Not really tested, I don't exactly know what OS gets set to on OS X.

**Comment by andmarti1424** [comment]
The thing is that sc-im now uses some specific functions that comes in ncursesw.. I believe plain ncurses would not work anymore.

**Comment by melak** [comment]
According to the Internet, OS X ncurses does have wide char support, so it may very well be the way to go.

Welcome to portability hell, enjoy your stay :)

**Comment by yokattana** [comment]
Yeah, this is what I tested yesterday. It builds and runs perfectly well just using `-lncurses`. Colours work too. I'll have a go with your approach.

**Pull request merged**
