### PR TITLE
many improvements to the config facility and usage

### PR DESCRIPTION
**Pull request by npitre**
Those are changes that are certainly going to improve performance
and make the code easier to understand.

### CODE REVIEW

**Comment by andmarti1424** [comment]
Thank you! Hope this wont break anything.
Question: why you decided to improve this, being improvements on other parts more needed?

**Comment by andmarti1424** [comment]
I got this warning btw:
conf.c: In function ‘store_default_config_values’:
conf.c:110:18: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  110 |     char *line = default_config;
      |                  ^~~~~~~~~~~~~~

**Comment by npitre** [comment]
On Sun, 21 Mar 2021, Andrés M. wrote:

> Question: why you decided to improve this, being improvements on other parts more needed?

Because that was in the way of something else I want to change and 
looking at that code made me cringe.

I didn't look at most of the code though. Where is more improvements 
needed?

**Comment by npitre** [comment]
On Sun, 21 Mar 2021, Andrés M. wrote:

> conf.c:110:18: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>   110 |     char *line = default_config;
>       |                  ^~~~~~~~~~~~~~

I'll fix it.

**Comment by andmarti1424** [comment]
Well, the main bug is with circular references, some of them makes sc-im crash. 

For instance if you set A0 to A0+A1 message "Circular reference shows up"
For instance if you set A0 to @sum(A0) it crashes..

Old SC used to evaluate the entire table on each change..doesnt matter if your change affect or not other cells. that was changed to a dependency graph.

Probably this validation should be handled in eval function of interp.c

**Comment by npitre** [comment]
> Well, the main bug is with circular references, some of them makes sc-im crash. 

Right. I reported #475 already.

That code is much less obvious.

**Comment by andmarti1424** [comment]
@npitre Yes. There is a problem with parse_str of dictionary.c
`:color type=HEADINGS fg=BLACK bg=YELLOW bold=1`
command doesnt work anymore.

**Comment by andmarti1424** [comment]
@npitre I made an urgent commit to recover that. Please give it a look. The parsing was not working properly.
Thanks.

**Comment by npitre** [comment]
> `:color type=HEADINGS fg=BLACK bg=YELLOW bold=1`
> command doesnt work anymore.

#526 should improve your fix. Let me know.

**Comment by andmarti1424** [comment]
@npitre Latest changes seems to work ok but it seems memory alloc'ed by strdup in function 'put' of dictionary.c is not freed and makes some memory leaks
on Valgrind..
Please check this out:


==7095== 2 bytes in 1 blocks are still reachable in loss record 1 of 296
==7095==    at 0x483E77F: malloc (vg_replace_malloc.c:307)
==7095==    by 0x4C6B5BE: strdup (in /usr/lib/libc-2.33.so)
==7095==    by 0x14AA34: put (dictionary.c:96)
==7095==    by 0x123FD9: set_colors_param_dict (color.c:177)
==7095==    by 0x1415E3: ui_start_screen (tui.c:137)
==7095==    by 0x13B71F: main (main.c:233)
==7095== 
==7095== 2 bytes in 1 blocks are still reachable in loss record 2 of 296
==7095==    at 0x483E77F: malloc (vg_replace_malloc.c:307)
==7095==    by 0x4C6B5BE: strdup (in /usr/lib/libc-2.33.so)
==7095==    by 0x14AA34: put (dictionary.c:96)
==7095==    by 0x124010: set_colors_param_dict (color.c:179)
==7095==    by 0x1415E3: ui_start_screen (tui.c:137)
==7095==    by 0x13B71F: main (main.c:233)

**Comment by andmarti1424** [comment]
@npitre forget about last message. I was seeing a log of what I am debugging... where I forced an exit and didnt free memory correctly

**Comment by npitre** [comment]
> @npitre forget about last message. I was seeing a log of what I am debugging... where I forced an exit and didnt free memory correctly

OK good. Because I was really puzzled.

**Pull request merged**
