### PR TITLE
Remove wcwidth and wcswidth declarations

### PR DESCRIPTION
**Pull request by yokattana**
These come in wchar.h

### CODE REVIEW

**Comment by andmarti1424** [comment]
Thanks.

**Comment by andmarti1424** [comment]
Now I get:

cmds_visual.c: In function ‘do_visualmode’:
cmds_visual.c:128:9: warning: implicit declaration of function ‘wcswidth’ [-Wimplicit-function-declaration]
         inputline_pos = wcswidth(inputline, real_inputline_pos);
         ^
cmds_edit.c: In function ‘do_editmode’:
cmds_edit.c:32:13: warning: implicit declaration of function ‘wcswidth’ [-Wimplicit-function-declaration]
             inputline_pos = wcswidth(inputline, real_inputline_pos);
             ^
cmds_edit.c: In function ‘del_back_char’:
cmds_edit.c:305:5: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
     int l = wcwidth(inputline[real_inputline_pos]);
     ^
utils/string.c: In function ‘count_width_widestring’:
utils/string.c:345:9: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
         c_width += wcwidth( s[n] );
         ^

**Comment by yokattana** [comment]
Interesting. What combination of OS/compiler/libc are you using?

**Comment by andmarti1424** [comment]
uname -r
3.16.0-4-kirkwood

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabi/4.9/lto-wrapper
Target: arm-linux-gnueabi
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armel/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armel --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armel --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv4t --with-float=soft --enable-checking=release --build=arm-linux-gnueabi --host=arm-linux-gnueabi --target=arm-linux-gnueabi
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by yokattana** [comment]
Might need to define `_XOPEN_SOURCE`:

**Comment by andmarti1424** [comment]
Added
#define _XOPEN_SOURCE
before
#include <wchar.h>
in utils/string.h
but still getting:

implicit declaration of function ‘wcwidth’
implicit declaration of function ‘wcswidth’

**Comment by andmarti1424** [comment]
same situacion with:
#define _POSIX_C_SOURCE = 200112L

**Comment by yokattana** [comment]
Should definitely not have an equals sign, sorry. In any case, this is something I'd be happy to figure out later. Feel free to revert this PR in the meantime.

**Comment by andmarti1424** [comment]
Try it without the '=' but with same results.
Dont know if an option to revert a pull request exists.. so I did a new commit.

**Comment by yokattana** [comment]
👍

**Pull request merged**
