### PR TITLE
make show_cursor a runtime selectable option

### PR DESCRIPTION
**Pull request by npitre**
"show_cursor" is the name of the option used with lynx and alpine to
produce the same effect.

### CODE REVIEW

**Comment by andmarti1424** [comment]
Hope this doesnt break anything.

**Comment by andmarti1424** [comment]
@npitre this latest PR I believe broke the validation of line 283 of color.c..
Or perjaps the parse_str..
This command now fails:
`color "type=HEADINGS fg=BLACK bg=YELLOW bold=1 dim=1"`

**Comment by andmarti1424** [comment]
@npitre ui question: do you think the command pending should be shown at the right of screen, just at the left of the mode?
and the current cell (lets say A0) at col 0 ??

**Comment by npitre** [comment]
I don't have a strong opinion about that. This is not something I'm 
really looking at. Command sequences are usually short enough that you 
rarely have to stop in the middle and wonder what is pending.

**Pull request merged**
