### PR TITLE
Open URL or file in cell

### PR DESCRIPTION
**Pull request by earthshrink**
Adds command `gf` to open URL or filename given in a cell. Invokes an included script _scopen_, so it can be customised by installation and overloaded in user's PATH. Command blocks on the script, so the script has the option to run a text mode browser like _w3m_ or editor like _vim_ in foreground, or return after launching a graphics mode browser like _firefox_ or editor like _gvim_ in background. Addresses issue #400.

Document file updated to also note exception to `gab24` (Issue #399)

### CODE REVIEW

**Comment by andmarti1424** [comment]
May be with the 'G' in uppercase to not collide with 'g' command..

**Comment by earthshrink** [comment]
I like the 'G' idea. Maybe we should also fix `gg` and `gl` for the same reason, viz that they prevent `goto` to columns `g` and `l`, respectively.

**Comment by andmarti1424** [comment]
Actually yes! You're right.

**Comment by andmarti1424** [comment]
@earthshrink actually 'G' collides as well. 'gt' may be the better option for goto cell..
btw, why you removed the line
sstderr = newterm(NULL, stderr, stdin);
?

**Comment by andmarti1424** [comment]
'g' command of NORMAL_MODE changed to 'gt'"

**Comment by earthshrink** [comment]
Re stderr, something was breaking at the time but seems no longer the case after rebasing to freeze tip. I didn't change 'gf' since you fixed the goto to 'gt'. thanks.

**Comment by andmarti1424** [comment]
Will merge this soon, but doc file and Makefile seems outdated.

**Comment by andmarti1424** [comment]
Already merged! Had to make some changes regarding conf since that changed a little. Thank you @earthshrink

**Comment by earthshrink** [comment]
Thanks so much, Andrés!
Apologize been unresponsive, been caught up in my research.

**Pull request closed without merging**
