### PR TITLE
Comments translate

### PR DESCRIPTION
**Pull request by alx741**
Ok, this translates the whole code base to English so future contributors will be able to help more easily.

This PR solves #7

### CODE REVIEW

**Comment by andmarti1424** [comment]
Hello and thanks again for your work.
some things i have noticed:

color.c:
// Initialize all possible 64 int pairs
should be
// Initialize all possible 64 init pairs

review macros.h since some comments were removed.

marks.c
-    // Al grabar una marca borro los rangos que utilizaban esa marca !!
+    // Delete marked ranges when recording a new one 
please add ("..with same char")

screen.c
 +    main_win: template loader window
 -    main_win: ventana que carga la planilla
please change to "window that loads the spreadsheet"

please review undo.c and yank.c files and retranslate them. some important comments were deleted.

rest is perfect!
thanks.

**Comment by alx741** [comment]
Sure, i'll take a look on that and come back to you later.

**Comment by alx741** [comment]
Ok, i've rebased from master and reviewed the files, make the corrections and retranslated some things. Lets see now...

**Comment by andmarti1424** [comment]
Thank you for your work. Already merged!

**Comment by andmarti1424** [comment]
Had to revert it because it did not compile! Can you check it out?

**Comment by alx741** [comment]
Oh! software is awesome, change the comments and it breaks! gajes del oficio. Let me see what happened...

**Pull request merged**
