### PR TITLE
display related fixes

### PR DESCRIPTION
**Pull request by npitre**
- abstract spreadsheet's available display size
- cleanups to ui_handle_mouse()
- let rescol adjust to the entire range
- improvements to ui_show_sc_col_headings()

### CODE REVIEW

**Comment by andmarti1424** [comment]
Thank you.

**Comment by andmarti1424** [comment]
Mouse support in insert and command got broken. Probably before your changes.

**Comment by npitre** [comment]
> Mouse support in insert and command got broken. Probably before your changes.

I have no mouse to test mouse support, sorry.

**Comment by andmarti1424** [comment]
DO not worry about it.

**Pull request merged**
