### PR TITLE
.mkd import, read write mardown, update docs

### PR DESCRIPTION
**Pull request by mipmip**
Refreshed version of an old PR branch. Ready to merge.

## Features
- sc-im can now import .mkd files
- when current file is .mkd is writes to .mkd format
- markdown column alignment is respected.
- doc and help are updated

When this is merged https://github.com/mipmip/vim-scimark should work with the vanilla sc-im

### CODE REVIEW

**Comment by mipmip** [comment]
With vanilla I mean the official sc-im.

**Comment by andmarti1424** [comment]
What do you mean by the official sc-im @mipmip. As far as I know I am the one who makes the official releases..

**Comment by mipmip** [comment]
> What do you mean by the official sc-im @mipmip. As far as I know I am the one who makes the official releases..

And thats the one I mean :) Vanilla in the sense of "no patched version"

**Comment by andmarti1424** [comment]
Thanks. Should probably implement this `when current file is .mkd is writes to .mkd format` to other formats as well to be consistent..

**Comment by mipmip** [comment]
> Thanks. Should probably implement this `when current file is .mkd is writes to .mkd format` to other formats as well to be consistent..

I needed this explicitly write back to the file. It might be useful for other for other formats. 

Thanks for the merge 😀 Have a nice weekend.

**Comment by mipmip** [comment]
I'm planning a vim-integration tutorial. Do you know when you will release the next sc-im version ?

**Pull request merged**
