### PR TITLE
Greek engfmt doc

### PR DESCRIPTION
**Pull request by earthshrink**
# Synopsis
Mainly documentation for 
* Greek and math symbols support (issue #356, implemented in PR #357)
* Engineering format support (issue #366, implemented in PR #395)

Also a fix for consistency in the engineering support.
Example for the Greek/math and engineering format: `tests/gps.sc`

### CODE REVIEW

**Comment by andmarti1424** [comment]
Great! Thanks!!

**Comment by andmarti1424** [comment]
how are you setting entire column format?
im using:
:int format A 12 2 2
for instance..
cause :format is setting just a cell or range, not an entire colum.
how are you doing it?

**Comment by earthshrink** [comment]
I inserted the command directly into `gps.sc`, consistent with the col format being a _a command available for scripting_, but yes, `:int format` is the right way to do using the UI.
thanks!

**Comment by andmarti1424** [comment]
May be I should fix the format function..

**Comment by earthshrink** [comment]
I was initially thinking on that line too, but as I read the code, realised there was a sufficient and consistent scheme in this case that made both an easy fix and right thing to do. Changing the function seems to need rethinking the column scheme from the classic _sc_.

**Pull request merged**
