### PR TITLE
Add updated Homebrew info to Readme

### PR DESCRIPTION
**Pull request by nickolasburr**
Hey @andmarti1424, I've decided to consolidate a few Homebrew taps I maintain into one, you can find it here: https://github.com/nickolasburr/homebrew-pfa. This PR is to update the Readme with that information in the Installation section.

### CODE REVIEW

**Comment by nickolasburr** [comment]
Also, assuming everything checks out on your end, could also update the wiki with the new tap URL? Thank you!

**Comment by andmarti1424** [comment]
Thanks!

**Comment by andmarti1424** [comment]
Feel free to update the wiki as well!

**Comment by nickolasburr** [comment]
All set 👍

**Pull request merged**
