### PR TITLE
travis setup with very simple testing using assert.sh

### PR DESCRIPTION
**Pull request by mipmip**
I created a very simple testing setup. You might want to enable travis for sc-im.

I included a very simple a bash testing framework https://github.com/lehmannro/assert.sh to keep the dependancies low.

### CODE REVIEW

**Comment by mipmip** [comment]
Please have a look at this PR. Now that Sc-im has more headless scripting features we can do a lot of continuous integration testing. This addition is free of complex dependancies. I can write instructions for contributors, how to write tests. When you get PR is would safe you a lot of time.

**Comment by mipmip** [comment]
Hello @andmarti1424 can you please give me feedback, or accept or defer this PR?

**Comment by andmarti1424** [comment]
I will do as soon as I can get to see those changes. Thanks.

**Comment by andmarti1424** [comment]
This work  is great. I am not planning to implement automatic tests riiiight now, but its a plan for the future if the project gets bigger and more collaborators join in. I know its the proper way of doing this and that is why I don't close this PR. Again thank you.

**Comment by andmarti1424** [comment]
Hello @mipmip. Thanks again for your work. I am thinking of starting to add some tests. I usually use valgrind to check there are no leaks or variable reading without initialization and stuff like that. Do you know if your work can be use with valgrind output as well?

**Comment by mipmip** [comment]
> Hello @mipmip. Thanks again for your work. I am thinking of starting to add some tests. I usually use valgrind to check there are no leaks or variable reading without initialization and stuff like that. Do you know if your work can be use with valgrind output as well?

I do not have a lot of experience with valgrind but it should work too. I would replace Travis with Github Actions as Travis has changed their free tier policy.

**Comment by andmarti1424** [comment]
I really liked your first approach. It goes well to test it with valgrind as well. I have commited the first test case. Thank you for your help.

**Comment by andmarti1424** [comment]
I am closing this. I have added a couple of tests and with Valgrind controls! Thanks for your work.

**Pull request closed without merging**
