### PR TITLE
improve cursor placement with show_cursor

### PR DESCRIPTION
**Pull request by npitre**
Using the column edge isn't clear on a braille display where screen
colors aren't visible, especially with empty cells.

Try to be smarter about cursor location.

This depends on PR #524

### CODE REVIEW

**Comment by andmarti1424** [comment]
I believe you keep the first commit (PR #525).
But I have already merged it!! Can you remove that from this one?

**Comment by andmarti1424** [comment]
btw Whats alpine??

**Comment by npitre** [comment]
> I believe you keep the first commit (PR #525).
> But I have already merged it!! Can you remove that from this one?

Done.

**Comment by npitre** [comment]
> btw Whats alpine??

A popular text-based email client:

https://en.wikipedia.org/wiki/Alpine_(email_client)

**Pull request merged**
