### PR TITLE
Support for lua 5.3

### PR DESCRIPTION
**Pull request by amuramatsu**

### CODE REVIEW

**Comment by andmarti1424** [comment]
@reportaman can you help me testing this?

**Comment by reportaman** [comment]
@andmarti1424 Sure! Btw, we should maintain the Lua API of sc-im in Lua 5.1 compatible syntax. The reason for that is LuaJIT is available only for that version. Also, the current version of Lua is 5.4, we should bump to that, and ideally we would support dynamic linking like this:  https://vi.stackexchange.com/a/18625, so users can choose what Lua version they want to link to without having to recompile.

**Comment by reportaman** [comment]
I did two of things:

1. Tried linking with luajit, and testing if it works. Yes, needs one change, which works with lua-5.1 too, and was probably a good idea to have in first place. The name ``luaL_reg`` was deprecated in Lua 5.1 (src: [here](http://lua-users.org/lists/lua-l/2016-03/msg00301.html)), it should always have been ``luaL_Reg``. Without this luajit, and future versions of Lua fail to compile. This needs updating one line in ``lua.c``.

2. Tried linking with lua-5.4, it fails to compile because ``luaL_register`` was removed. [src-1]( http://lua-users.org/lists/lua-l/2013-05/msg00168.html) mentions a new recipe using; [src-2](http://lua-users.org/wiki/CompatibilityWithLuaFive) mentions a compatible way of migrating (look at the bottom of page) , [src-3](https://github.com/nodemcu/nodemcu-firmware/issues/2808) gives a complete higher level list for migration (you might not need this).

**Comment by reportaman** [comment]
@andmarti1424 Ah I see, I cloned @amuramatsu's changes, they look good in my testing. Btw, it given his makefile looks for pkg-config "lua", it will automatically link to whatever lua user is using (5.1/2/3 or 5.4). Given I have the latest lua installed, it linked to lua 5.4.2. 

The testing is limited because of some bug introduced by your latest commit that added ``@ston`` to dependency graph.

1. Lua scripts that write to the same cell in which they are triggered from using ``=@ston(@lua("scriptname.lua",0))``, end up writing the cell with ``0.00`` when ``@ston`` finishes; that overwrites whatever ``<value>`` user intended to write to the cell using ``sc.lsetnum(sc.curcol(),sc.currow(), <value>)`` .
2. Lua scripts with``sc.lquery`` are misbehaving. This is what I notice: If have a ``sc.lquery`` in a script, with every run of ``=@ston(@lua("scriptname",0))`` the number of times user has to enter carriage return increases by one. So, if I am running the script Nth time (sequentially from N different cells), I need to hit ``<CR>`` N times before it would actually capture the user input & complete to move to the next lua statement.

While @amuramatsu's change looks good, I think we should wait for the upstream bug fix so more comprehensive testing can be done before this is pushed.

**Comment by andmarti1424** [comment]
About the patch, yes please!

**Comment by andmarti1424** [comment]
@reportaman did you happen to create a new patch with it? thanks.

**Comment by reportaman** [comment]
@andmarti1424 I have created a separate pull request. Please reject this, and accept that.

**Comment by andmarti1424** [comment]
@amuramatsu Thank you. Already merged by @reportaman .

**Pull request closed without merging**
