### PR TITLE
Add new command p and P in visual mode.

### PR DESCRIPTION
**Pull request by wimstockman**
Paste into the visual area. Repeating the yanked area.
p is normal paste
P is like Pc adjust the cell references
addressing the Feature request: Paste to a range of selected cells #438

### CODE REVIEW

**Comment by leg7** [comment]
Much needed change.

**Comment by andmarti1424** [comment]
Does this support the undo of the paste as well?

**Comment by wimstockman** [comment]
yes, it does supporr undo it uses the same functions as the paste commands from normal mode

**Comment by wimstockman** [comment]
thx :-)

**Pull request merged**
