### PR TITLE
Add italic option to colors

### PR DESCRIPTION
**Pull request by bentitmus**
Italic is supported by xlsxwriter and ncurses (since 5.10 which is now quite old).

### CODE REVIEW

**Comment by andmarti1424** [comment]
Thank you!

**Comment by andmarti1424** [comment]
I merged it. but I am not able to see it in italic. Dont know if its a terminal issue or ncurses??

**Comment by bentitmus** [comment]
I'm not completely familiar with these things, but it is often a terminal issue. Maybe try in another terminal. If you are using tmux, then try without as that can cause issues. I've just tried master on macOS and it works in the usual macOS terminal. I've also tried in a few different terminals in Linux before I submitted the pull request. Interestingly it now doesn't build with the default ncurses on macOS so you need the homebrew ncurses (and to modify the Makefile to point it in the direction of the correct ncurses to use).

**Comment by andmarti1424** [comment]
Yes. It is. I use linux. Tried three different terminals and in two different machines with same behaviour. Will try to figure it out.  Thanks.

**Comment by bentitmus** [comment]
This [superuser page](https://superuser.com/questions/1514762/italics-work-everywhere-except-in-less1) (and the linked reddit page) might help.

**Comment by andmarti1424** [comment]
Confirmed.  It works ok.
It depend on the terminal you use and of course in how you setup the TERM environment variable.
In my case italics works with: TERM=xterm-256color ./sc-im
THANK YOU!

**Pull request merged**
