### PR TITLE
Clarify color and cellcolor arguments

### PR DESCRIPTION
**Pull request by melak**
A bit of digging in gram.y reveals that color specification to the color
and setcolor commands is actually one argument.

Spell this fact out clearly in the documentation.

### CODE REVIEW

**Comment by melak** [comment]
Yes, it it. The color spec itself is not part of the grammar, but the argument is passed to `chg_color()` and `color_cell()` as one parameter. It's pretty easy to try, though:
```
$ cat exbad.sc 
cellcolor A0 fg=BLACK bg=WHITE
```
```
$ cat exgood.sc 
cellcolor A0 "fg=BLACK bg=WHITE"
```
Just try opening both.

Updated the PR with the fix on cellcolor, thanks.

**Comment by andmarti1424** [comment]
The thing is the following:
:cellcolor is taken first in cmds_command.c
There it checks if a range is selected, otherwise it changes current cell.
It does not take a range as an argument directly.
for that, you have to do:
:int cellcolor A0:B3 "bg=RED fg=WHITE"
in that case fullquoted, yes.

We have to change cmds_command.c if you want cellcolor to handle a range directly (in command mode), and not by the interpreter itself.
As you were adding the command to your file directly, its the same as sending the command to the interpeter..

**Comment by melak** [comment]
We are talking about differen things. I am talking about inputs from a _file_, hence the _"[...] when specified in a file [...]"_ stanza on both counts.

When reading from a file, lines go through the parser before anything else (cf. `file.c:457`).
```
color fg=RED bg=WHITE bold=1
```
(*without* the quotes) _will_ be rejected by the parser.

To clarify, I am _not_, in any way, touching on the _interactive_ aspect. They do seem to be somewhat different (which is not very intuitive, but that's for another day), and I don't care about the interactive use in this specific case.

Try setting your color scheme in `.scimrc`, it'll become pretty apparent.

**Comment by andmarti1424** [comment]
Yes, i understood your point. i know the parser will reject it without the full quotes.what i meant is that in doc file, the comment applies to the command to be used from command mode.. Not sending it directly to the parser.. That is why it does not specify that it receives a range as a parameter..

**Comment by andmarti1424** [comment]
I believe we should change cmds_command to first check if a range or cell is passed as argument. If not, check if a range is selected. And if not, just make the change to current cell. Doing that, we can add to doc that the command can receive a range as a parameter..

**Comment by melak** [comment]
Just so we are on the same page again, are you saying `cellcolor` cannot take a range spec?

**Comment by andmarti1424** [comment]
That is what i am saying. The :cellcolor command of command mode does not receive a range as an argument. You could send to the parser this:
:int cellcolor A4:A6 "bg=blue"    
 if you need to specify a range.. But sending commands directly to the parser is probably not a good thing to do

**Comment by melak** [comment]
OK, I see now what your problem with the diff is. Yes, your proposal does fix the immediate issue, although on a greater scale, I think this "sometimes parser, sometimes not" thing will lead to more confusion.

**Comment by andmarti1424** [comment]
Made some changes. Please try them out.
Now :cellcolor can receive a range as a parameter.
You can :cellcolor A2:B4 "bg=BLUE"
or you can just :cellcolor "bg=BLUE". In the later case it affects just the selected cell or range.
It always should be fullquoted. Updated doc as well.

**Comment by melak** [comment]
OK, this seems to work, thanks. Now back to `color`: the command line now accepts both quoted or unquoted forms, but from file, it's only quoted. This is fine, though, but the doc still needs some adjustments. My suggestion:

```
diff --git a/src/doc b/src/doc
index 944f63f..5b8db06 100644
--- a/src/doc
+++ b/src/doc
@@ -603,7 +603,7 @@ Commands for handling cell content:
                 Apply a left padding {spaces} characters in width to a column.
                 If a range selected, pad the columns inside that range.
 
-    :color {key}={arg} ..
+    :color "{key}={arg} .."
                 Change a color definition.
 
                 {key} is one of the following:
@@ -621,13 +621,13 @@ Commands for handling cell content:
 
                 The value of other parameters are booleans, 1 or 0.
 
-                Example:  :color type=HEADINGS bold=0 fg=BLACK bg=YELLOW
+                Example:  :color "type=HEADINGS bold=0 fg=BLACK bg=YELLOW"
 
                 Colors can be set at runtime or specified in:
                      a. the .scimrc file stored in $HOME
                      b. the current .sc file.
 
-    :cellcolor {key}={arg} ..
+    :cellcolor "{key}={arg} .."
                 Change the color of the current cell or range.
                 Example:   :cellcolor "bg=CYAN fg=WHITE"
                            :cellcolor "fg=RED bold=1 underline=1"
```

This will be fine in either command mode or from a file, and there's no need to separate these in the documentation.

**Comment by andmarti1424** [comment]
I am afraid I merge it by mistake thinkinh you added this you commented in the pull request..

**Comment by melak** [comment]
No, not yet, but never mind, I'll open a new one.

**Pull request merged**
